[BACKPORT]:RTW88:Import from 4.14 + patch for 4.19
Imported RTW88 directory from 4.14 Kernel

Source : https://github.com/yesimxev/android_kernel_xiaomi_sm6125/commit/a78504f41f4bcddea43b380aed2f142a55709d19#diff-83ed3e5794817476b02b34233db160cc552eeec3472430d549581976b2a8f00f

- Copied rtw88 directory from android_kernel_xiamo_sm6125
- Manually made the change to include/linux/mmc/sdio_ids.h and
include/net/mac80211.h for 4.19
- The file at include/uapi/linux/nl80211.h doesnt needed any change in
  4.19

Additional change was needed for 4.19

- quirks.h:197:37: error: use of undeclared identifier 'SDIO_DEVICE_ID_MARVELL_8887WLAN'
- Patched drivers/mmc/core/quirks.h

"SDIO_DEVICE_ID_MARVELL_8887WLAN" to "SDIO_DEVICE_ID_MARVELL_8887_WLAN"

- rtw8723cs.c:21:27: error: unused variable 'rtw_8723cs_driver'
- same error affected rtw8822cs.c rtw8723ds.c rtw8821cs.c rtw8822bs.c
- Patched drivers/net/wireless/realtek/rtw88/rtw8723cs.c and rtw8822cs.c
  rtw8723ds.c rtw8821cs.c rtw8822bs.c

"module_sdio_driver(struct sdio_driver rtw_8723cs_driver);" to "module_driver(rtw_8723cs_driver,
sdio_register_driver,
sdio_unregister_driver);"